### ISSUE TITLE
Split into server pregeneration vs on router execution

### ISSUE THREAD

**Issue by k-nut** [freifunk-berlin/firmware-wizard-frontend#10]
There are two ways of operation for the new wizard: On the freifunk servers. This will allow you to selecdt your router, make your settings and then download an image that has been configured for you. For this use case the users also needs to select her router model.

The wizard can also be executed on the router directly after flashing. 

Maybe we should only focus on the second option for now?

**Comment by andrenarchy** [comment]
Config generation works fine now on the server and on the actual device. If the config is supposed to be baked into an image then this should be tracked elsewhere.
