### ISSUE TITLE
IP addresses

### ISSUE THREAD

**Issue by cholin** [freifunk-berlin/firmware-wizard-frontend#3]
Ein Erklärtext was IP-Adressen sind, wäre schön. Also in etwas "Damit dein Router unter einer Adresse erreichbar für andere ist, brauchst du eine IP-Adresse." Noch dazu woher kriege ich diese Adressen (http://config.berlin.freifunk.net).

**Comment by andrenarchy** [comment]
PRs are welcome

**Comment by geirkairam** [comment]
done with #16
