### ISSUE TITLE
VPN settings: add possibility to upload openvpn config file

### ISSUE THREAD

**Issue by andibraeu** [freifunk-berlin/firmware-wizard-frontend#36]
we want to enable people to add other vpn servers not preconfigured in firmware

**Comment by andibraeu** [comment]
I think it's better to store contents of the files (config, cert, pub key) within the json and the backend will restore them into files.

that will work with both, the router and the online wizard

**Comment by andrenarchy** [comment]
yes, this is what I meant with file "upload". In fact we just want to transform them into base64 and store them in the `config.json`.
