### ISSUE TITLE
control-chars in ip-address field

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/firmware-wizard-frontend#86]
in the code used on hackathon (18.02.2017) there was in all ip-address-fields a "&#10;" suffixed to the example

see mesh3 in screenshot
![ff-wizard3-bug nsm5_ipaddress foo](https://cloud.githubusercontent.com/assets/1755362/23193315/8dc8f912-f8a8-11e6-8298-dd705bfbcb20.png)

**Comment by andibraeu** [comment]
that seems to be an error in our translated file. We have to fix it at transifex and regenrate the file

**Comment by andrenarchy** [comment]
fixed in #89
