### ISSUE TITLE
olsr configuration doesn't link to the correct library

### ISSUE THREAD

**Issue by andibraeu** [freifunk-berlin/firmware-wizard-frontend#92]
wrong:
```option library 'olsrd_txtinfo'```

correct:
```option library 'olsrd_txtinfo.so.0.1'```

**Comment by andrenarchy** [comment]
I guess this is a backend issue? Can you reopen in the berlin packages repo?

**Comment by andibraeu** [comment]
I tried my very best, but issues aren't enabled there...

**Comment by andrenarchy** [comment]
Oh, you're right, sorry! I think we collected those with a `wizard-backend` label in https://github.com/freifunk-berlin/firmware/issues?q=is%3Aopen+is%3Aissue+label%3Awizard-backend

**Comment by andrenarchy** [comment]
Do you want to reopen there?

**Comment by andibraeu** [comment]
is it done now? I think so...

**Comment by andrenarchy** [comment]
I think so too. Reopen in the firmware repo if this is still an issue.
